mongodb:
  build: ./mongodb
  ports:
    - "27017"
  volumes:
    - ./mongodb/data/db:/data/db

qckblg:
  build: ./qckblg
  ports:
    - "9000"
  links:
    - mongodb

tonic:
  build: ./tonic
  ports:
    - "9000"

trnscld:
  build: ./trnscld
  ports:
    - "30000"

hrvrd:
  build: ./hrvrd
  ports:
    - "30000"

clck:
  build: ./clck
  ports:
    - "30000"

nfnt:
  build: ./nfnt
  ports:
    - "30000"

nginx:
  build: ./nginx
  ports:
    - "80:80"
  links:
    - tonic
    - qckblg
