mongodb:
  build: ./mongodb
  volumes:
    - ./mongodb/data/db:/data/db

qckblg:
  build: ./qckblg
  ports:
    - "9000"
  links:
    - mongodb

tonic:
  build: ./tonic
  ports:
    - "9000"

nginx:
  build: ./nginx
  ports:
    - "80:80"
  links:
    - tonic
    - qckblg
